---
- name: american locale
  locale_gen: name=en_US.UTF-8 state=present

- name: polish locale
  locale_gen: name=pl_PL.UTF-8 state=present

- name: update package info
  apt: update_cache=yes cache_valid_time=3600

- name: upgrade system
  apt: upgrade=dist
