---
- name: switch compositor to opengl3.1
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.config/kwinrc"
    line: GLCore=true
    regexp: '^GLCore='

- name: prevent tearing on pc
  when: not on_laptop
  become: true
  lineinfile:
    dest: /etc/profile.d/tearing.sh
    line: export KWIN_TRIPLE_BUFFER=1
    regexp: '^export KWIN_TRIPLE_BUFFER='
    create: yes

- name: set desktop konsole font size
  when: not on_laptop
  set_fact: konsole_font_size=10

- name: set laptop konsole font size
  when: on_laptop
  set_fact: konsole_font_size=11

- set_fact: konsole_conf_dir={{ ansible_env.HOME }}/.local/share/konsole

- name: set konsole profile
  template: src=Butla.profile dest={{ konsole_conf_dir }}

- name: set konsole settings
  copy: src=konsole/{{ item.src }} dest={{ item.dest }}
  with_items:
  - { src: Linux.colorscheme, dest: "{{ ansible_env.HOME }}/.local/share/konsole" }
  # this will report getting changed after system reboot
  - { src: konsolerc, dest: "{{ ansible_env.HOME }}/.config" }

- name: set custom shortcuts
  copy: src=khotkeysrc dest={{ ansible_env.HOME }}/.config

- name: modify global shortcuts
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.config/kglobalshortcutsrc"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  with_items:
  # first three are getting changed by system at reboot, but they work fine...
  - { line: 'Lock Session=Meta+L,none,Lock Session', regexp: '^Lock Session=' }
  - { line: 'MoveZoomDown=none,none,Move Zoomed Area Downwards', regexp: '^MoveZoomDown=' }
  - { line: 'show dashboard=Meta+D,none,Show Desktop', regexp: '^show dashboard=' }
  - line: 'Walk Through Windows=Alt+Tab,none,Walk Through Windows'
    regexp: '^Walk Through Windows='
  - line: 'Walk Through Windows (Reverse)=Alt+Shift+Backtab,none,Walk Through Windows (Reverse)'
    regexp: '^Walk Through Windows \(Reverse\)='
  - { line: 'Window Maximize=Meta+Up,none,Maximize Window', regexp: '^Window Maximize=' }
  - { line: 'Window Minimize=Meta+Down,none,Minimize Window', regexp: '^Window Minimize=' }
  - line: 'Window Quick Tile Left=Meta+Left,none,Quick Tile Window to the Left'
    regexp: '^Window Quick Tile Left='
  - line: 'Window Quick Tile Right=Meta+Right,none,Quick Tile Window to the Right'
    regexp: '^Window Quick Tile Right='
  - line: 'Window to Next Screen=Meta+Shift+Left,none,Window to Next Screen'
    regexp: '^Window to Next Screen='
  - line: 'Window to Previous Screen=Meta+Shift+Right,none,Window to Previous Screen'
    regexp: '^Window to Previous Screen='
  - line: 'activate widget 2=Meta+Q,none,Activate Application Launcher Widget'
    regexp: '.*Activate Application Launcher Widget$'
  - line: 'manage activities=none,Meta+Q,Activities...'
    regexp: '^manage activities='

- name: modify laucher hotkey
  replace:
    dest: "{{ ansible_env.HOME }}/.config/plasma-org.kde.plasma.desktop-appletsrc"
    regexp: '\[Containments\]\[1\]\[Applets\]\[2\]\[Shortcuts\]\nglobal=.*'
    replace: '[Containments][1][Applets][2][Shortcuts]\nglobal=Meta+Q'

# KUBUNTU
# kalkulator na guzik kalkulatora

#- polskie ustawienia daty, liczb, itp (ale nie cały region)
#- zegar z sekundami i datą, bold
#- system setting/startup and shutdown/"start with an empty sesssion", też default leave option: turn off computer
#- "Configure automatic handling of removable storage media" -> "Enable automatic mounting of removable media"
#- schować w treyu: komunikatory, organizer deamon
#- w vlc przewijanie na strzałki, zamiast shift+strzałki. Navigate left/right ustawić na shift+strzałki.
#- docker (install z ppa?)
#- apt install sshpass (żeby można było konfigurować raspberry)
# pycharm z ustawieniami
# pycharm, keepass, ktorrent do favouritów
# wyłączenie launchera na lapku

# GŁÓWNY
# mount danych
# klucz prywatny do backupów
# backup (już nic do dropboxa, wszystko na dysk)
# bookmarks w rangerze
# thunderbird i ustawienie jego backup, muszę zgrać jego dotychczasowe wiadomości?
