---
# TODO check if too much clementine's config comes from B2
# TODO gimp single window mode

- name: add dropbox repository
  apt_repository: repo='deb http://linux.dropbox.com/ubuntu xenial main'
  become: true

- name: add dropbox package key
  apt_key: keyserver=pgp.mit.edu id=5044912E
  become: true

- name: install python-gpgme for dropbox bootstrap
  apt: name=python-gpgme
  become: true

# TODO get rid of unauthorized deb workaround when they fix it
#- name: install dropbox
#  apt: name=dropbox update_cache=yes
#  become: true
- name: install dropbox
  command: apt-get install -y --allow-unauthenticated dropbox
  register: dropbox_install
  changed_when: dropbox_install.stdout.find('is already the newest') == -1
  become: true

- name: start and install dropbox daemon
  command: dropbox start -i
  register: dropbox_start
  changed_when: dropbox_start.stdout.find('is already running!') == -1

- name: create keepass configuration directory
  file: path={{ ansible_env.HOME }}/.config/KeePass state=directory

- name: set keepass configuration
  copy: src=KeePass.config.xml dest={{ ansible_env.HOME }}/.config/KeePass

- name: add inkscape repository
  apt_repository: repo=ppa:inkscape.dev/stable
  become: true

- name: install additional programs
  apt: name={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
  - chromium-browser
  - clementine
  - gimp
  - gthumb
  - hunspell
  - inkscape
  # user needs to log in with Dropbox before running keepass
  - keepass2
  - synaptic
  - vlc
  become: true

- name: create GnuPG config directory
  file: path={{ ansible_env.HOME }}/.gnupg state=directory

- name: set configuration in HOME directory
  copy: src={{ item }} dest={{ ansible_env.HOME }}
  with_items:
  - .gnupg
  - .pypirc

- name: install twine
  pip: name=twine executable=pip3 extra_args=--user

- name: set ranger bookmarks
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.config/ranger/bookmarks"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    create: yes
  with_items:
  - { line: "c:{{ ansible_env.HOME }}/Dropbox", regexp: "^c:" }
  - { line: "D:{{ ansible_env.HOME }}/Downloads", regexp: "^D:" }
  - { line: "w:{{ ansible_env.HOME }}/development", regexp: "^w:" }
  - { line: "h:{{ ansible_env.HOME }}", regexp: "^h:" }

